### ISSUE TITLE
Thanks for the efi file, works! great

### ISSUE THREAD

**Issue by a42014** [alexleisyd/lenovo-m90n-hackintosh#1]
Just don't know how to make wifi work, change the DW1820A, don't know how to do the "Pin masking"

**Comment by alexleisyd** [comment]
Hi, I have added the photos to the repo. Further details can be found on [this link](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html).

**Comment by a42014** [comment]
So great! really detailed and helpful.
Thanks!
