### ISSUE TITLE
Why MacBookPro15,2 instead of Macmini8,1

### ISSUE THREAD

**Issue by BrushXue** [alexleisyd/lenovo-m90n-hackintosh#2]
This is a NUC-like computer.  And it doesn’t have a trackpad. Is there any specific reason using the MacBook SMBIOS?

**Comment by alexleisyd** [comment]
There isn't. I guess you can try and use the iMac SMBIOS or Mac Mini.

**Comment by BrushXue** [comment]
I tested macmini8,1 and it worked. However the audio is still not perfect. With alcid=11, the speaker works, but no sound from the audio jack.
Edit: if I insert a headphone before the system boots, there will be sound in the headphone, but the speaker will be unavailable.

**Comment by telus2009** [comment]
Thank you for your sharing, but there is a problem. When I connect the 4K display, the maximum resolution is only 2K, and the display is very fuzzy. How to solve this problem? There is another problem, the default is to turn on the speaker of the host. My monitor has a built-in audio. You have to plug in the display cable every time to find the audio. Please reply if you see it. Thank you!

**Comment by BrushXue** [comment]
You can check my fork. You need setup 64MB DVMT in the BIOS to get 4k. As for the audio, I have the same issue.


> Thank you for your sharing, but there is a problem. When I connect the 4K display, the maximum resolution is only 2K, and the display is very fuzzy. How to solve this problem? There is another problem, the default is to turn on the speaker of the host. My monitor has a built-in audio. You have to plug in the display cable every time to find the audio. Please reply if you see it. Thank you!

**Comment by telus2009** [comment]
Is this the setting? But it doesn't work. Can you tell me where the BIOS options are? Thank you again. You've helped me a lot.
![2020_08_30_02_49_IMG_0431](https://user-images.githubusercontent.com/59395459/91644256-f66e1b00-ea6c-11ea-9d31-8414f0f80130.JPG)
![2020_08_30_02_55_IMG_0432](https://user-images.githubusercontent.com/59395459/91644260-f8d07500-ea6c-11ea-8b45-d7f4be210460.JPG)

**Comment by BrushXue** [comment]
我就在BIOS里调的这个，别的关于hidpi的软件没有安装过，原生4k。

**Comment by telus2009** [comment]
Are you connected to the DP interface? I am currently connected to the back of the typc interface

**Comment by BrushXue** [comment]
I tested USB-C, DP and USB-C to HDMI adapter, all of them have native 4k60. My monitor is U2720Q.

**Comment by telus2009** [comment]
大哥原来也是说中文，我还搞翻译软件，哈哈。

**Comment by BrushXue** [comment]
你再试试吧，这个机器除了耳机插孔之外应该是完美的。有时候没有4k可能是显示器edid没识别之类的

**Comment by telus2009** [comment]
好的，谢谢你的回复，后续更新请告知，好人一生平安。

**Comment by telus2009** [comment]
https://www.chiphell.com/thread-2211560-1-1.html,这位兄弟的贴子，可以参考下，我pm他可惜没有回复

**Comment by BrushXue** [comment]
你可以试试我的config.plist，这个repo用的是MacBook Pro，我用的是Mac mini，稍有区别

**Comment by telus2009** [comment]
我就是用你整个的efi的，没作任何改动，为什么我的机型却是Macbook Pro?  奇怪，您能重新打包一份你目前完整efi给我吗？可以的话发我邮箱：14622127@qq.com。谢谢你啊

**Comment by BrushXue** [comment]
不可能啊，你下载错了吧？
![39997431-8655-493C-9D4B-48460195200B](https://user-images.githubusercontent.com/12702149/91645023-9432fd00-ea0f-11ea-86c9-64349a0020e5.png)

**Comment by telus2009** [comment]
是的。刚重新下载你的efi，将本机EFI删除再替换也是一样，机型也是pro，也不知道什么原因。明天格式化重装再试了，再次感谢您的热心帮助，如果可以的话，能否加qq好友？邮箱就是我号码，然后再次请求打包一份你目前正常使用的EFI发给我，万分感激，时间不早了，早点休息。晚安！

**Comment by BrushXue** [comment]
我不用qq...另外我目前正常使用的efi就是GitHub上面的这个，只是加了序列号而已。

**Comment by alexleisyd** [comment]
> I tested macmini8,1 and it worked. However the audio is still not perfect. With alcid=11, the speaker works, but no sound from the audio jack.
> Edit: if I insert a headphone before the system boots, there will be sound in the headphone, but the speaker will be unavailable.

Thanks for letting me know. I will play around in the next weeks when I have some spare time.

**Comment by telus2009** [comment]
> 不可能啊，你下载错了吧？
> ![39997431-8655-493C-9D4B-48460195200B](https://user-images.githubusercontent.com/12702149/91645023-9432fd00-ea0f-11ea-86c9-64349a0020e5.png)
用了你的EFI，4K正常了，但是我的WIFI和蓝牙却打不开了，我的是免驱的BCM94352Z

**Comment by BrushXue** [comment]
94352z不是94360NG那种真免驱，你还是得加kext。你把两个配置文件揉在一起应该就可以了。具体怎么操作我没有这张卡也不知道。

**Comment by telus2009** [comment]
Guanyang Xue <notifications@github.com>于2020年8月30日 周日下午10:52写道：

**Comment by telus2009** [comment]
> 94352z不是94360NG那种真免驱，你还是得加kext。你把两个配置文件揉在一起应该就可以了。具体怎么操作我没有这张卡也不知道。

大神，我把驱动打上之后，开机就会丢失引导，只剩WIN了
![2020_08_31_15_34_IMG_0447](https://user-images.githubusercontent.com/59395459/91695150-4994ba80-eba0-11ea-8c51-3c0f3ce73543.JPG)

**Comment by telus2009** [comment]
升级了6.0的opencore，所有驱动完美了，包括耳机孔，显示器声音都完美了，如果你需要efi，留下邮箱我给你发

**Comment by BrushXue** [comment]
大哥，这里是github啊，你自己fork一下然后上传efi不就好了...

**Comment by BrushXue** [comment]
> 升级了6.0的opencore，所有驱动完美了，包括耳机孔，显示器声音都完美了，如果你需要efi，留下邮箱我给你发

算了，我估计你也不太会操作git，你直接把zip打包拖到这里回复就可以了。

**Comment by telus2009** [comment]
opencore6.0 M90n 
[EFI6.0.zip](https://github.com/alexleisyd/lenovo-m90n-hackintosh/files/5150943/EFI6.0.zip)
